/**
 * Models describing the data served by the local OpenCode HTTP server.
 *
 * Only the fields the OpenCode tab actually renders are typed here; the server
 * returns a much larger payload and every unknown field is simply ignored.
 */

/**
 * The state of the local OpenCode server owned by the main process.
 *
 * A single server instance serves every repository — requests are scoped to a
 * repository by passing its path as the `directory` query parameter.
 */
export interface IOpenCodeServerStatus {
  /** Whether the server is listening and ready to accept requests. */
  readonly running: boolean

  /** The base URL (e.g. `http://127.0.0.1:41234`), or null when not running. */
  readonly baseUrl: string | null

  /**
   * The randomly generated password the server was started with. Sent as HTTP
   * basic auth on every request so that other local processes can't drive the
   * server. Null when the server isn't running.
   */
  readonly password: string | null

  /** A human readable reason why the server isn't running, or null. */
  readonly error: string | null
}

/** A conversation as listed by `GET /session`. */
export interface IOpenCodeSession {
  /** The session identifier (`ses_…`). */
  readonly id: string

  /** Set on sessions spawned by a subagent; those are hidden from the list. */
  readonly parentID?: string

  /** The working directory the session belongs to. */
  readonly directory: string

  /** The session title, generated by OpenCode from the first prompt. */
  readonly title?: string

  /** The agent that handled the session, when known. */
  readonly agent?: string

  /**
   * The model the session last ran with, recorded by the server. Restored into
   * the picker when the conversation is reopened.
   *
   * `variant` is `'default'` rather than absent when no reasoning preset was
   * used.
   */
  readonly model?: {
    readonly id: string
    readonly providerID: string
    readonly variant?: string
  }

  /** Accumulated cost in USD. */
  readonly cost?: number

  /** Creation/last update timestamps in milliseconds since the epoch. */
  readonly time: {
    readonly created: number
    readonly updated: number
  }
}

/** The role of a message in a conversation. */
export type OpenCodeMessageRole = 'user' | 'assistant'

/** The envelope describing a message, without its parts. */
export interface IOpenCodeMessageInfo {
  readonly id: string
  readonly sessionID: string
  readonly role: OpenCodeMessageRole

  /** Present on assistant messages. */
  readonly agent?: string

  /** Present on assistant messages. */
  readonly modelID?: string

  /** Present on assistant messages. */
  readonly providerID?: string

  /**
   * Set when the assistant run failed. The shape varies by error kind so it is
   * rendered through {@link getOpenCodeErrorText}.
   */
  readonly error?: unknown

  readonly time: {
    readonly created: number
    /** Set once the assistant finished producing the message. */
    readonly completed?: number
  }
}

/** A plain text part — the visible prose of a message. */
export interface IOpenCodeTextPart {
  readonly id: string
  readonly type: 'text'
  readonly text: string
}

/** A reasoning ("thinking") part, rendered collapsed by default. */
export interface IOpenCodeReasoningPart {
  readonly id: string
  readonly type: 'reasoning'
  readonly text: string
}

/** The lifecycle state of a tool invocation. */
export interface IOpenCodeToolState {
  readonly status: 'pending' | 'running' | 'completed' | 'error'
  readonly input?: Record<string, unknown>
  readonly output?: string
  readonly error?: string
  readonly title?: string
}

/** A tool invocation part. */
export interface IOpenCodeToolPart {
  readonly id: string
  readonly type: 'tool'
  readonly callID: string
  readonly tool: string
  readonly state: IOpenCodeToolState
}

/** A file attached to a message. */
export interface IOpenCodeFilePart {
  readonly id: string
  readonly type: 'file'
  readonly filename?: string
  readonly mime?: string
  readonly url?: string
}

/** Any part kind the UI doesn't render (`step-start`, `step-finish`, …). */
export interface IOpenCodeOtherPart {
  readonly id: string
  readonly type: string
}

/** A single element of a message's content. */
export type OpenCodePart =
  | IOpenCodeTextPart
  | IOpenCodeReasoningPart
  | IOpenCodeToolPart
  | IOpenCodeFilePart
  | IOpenCodeOtherPart

/** A message together with all of its parts. */
export interface IOpenCodeMessage {
  readonly info: IOpenCodeMessageInfo
  readonly parts: ReadonlyArray<OpenCodePart>
}

/** A model offered by a provider, as listed by `GET /config/providers`. */
export interface IOpenCodeModel {
  readonly id: string
  readonly name?: string

  /**
   * Reasoning presets the model supports, keyed by name (`low`, `high`,
   * `max`, …). Absent when the model has none.
   */
  readonly variants?: Record<string, unknown>
}

/** A provider and the models it offers. */
export interface IOpenCodeProvider {
  readonly id: string
  readonly name?: string
  readonly models: Record<string, IOpenCodeModel>
}

/** The model picked for a prompt. */
export interface IOpenCodeModelSelection {
  readonly providerID: string
  readonly modelID: string
}

/** One entry of the model picker, flattened out of the provider list. */
export interface IOpenCodeModelOption {
  readonly providerID: string
  readonly providerName: string
  readonly modelID: string
  readonly modelName: string
  /** The variant names this model accepts, empty when it has none. */
  readonly variants: ReadonlyArray<string>
}

/**
 * A file sent along with a prompt: either attached from disk or referenced
 * with `@path` in the message text.
 */
export interface IOpenCodeAttachment {
  /** The path shown in the UI, relative to the repository when possible. */
  readonly path: string
  /** The file name. */
  readonly filename: string
  /** The MIME type, guessed from the extension. */
  readonly mime: string
  /**
   * The content as a data URL for an attachment, or a `file://` URL for a
   * reference the server reads itself.
   */
  readonly url: string
  /** Whether this came from an `@path` reference rather than a file picker. */
  readonly isReference: boolean
}

/** A prompt waiting for the current run to finish before it is sent. */
export interface IOpenCodeQueuedPrompt {
  /** Identifier used to drop a single entry from the queue. */
  readonly id: string
  readonly text: string
  readonly attachments: ReadonlyArray<IOpenCodeAttachment>
}

/** An agent as listed by `GET /agent`. */
export interface IOpenCodeAgent {
  readonly name: string
  readonly description?: string

  /**
   * `primary` agents can be picked for a conversation; `subagent` ones are only
   * invoked by other agents and are therefore hidden from the picker.
   */
  readonly mode?: string
}

/**
 * A permission the agent is waiting on before it can run a tool. Surfaced
 * inline in the conversation with allow/reject actions.
 */
export interface IOpenCodePermissionRequest {
  readonly id: string
  readonly sessionID: string

  /** The permission being requested, e.g. `bash` or `edit`. */
  readonly permission: string

  /** The concrete resources covered by the request (paths, commands, …). */
  readonly patterns?: ReadonlyArray<string>

  /** Tool-specific details such as the command line about to be run. */
  readonly metadata?: Record<string, unknown>
}

/** The answer to an {@link IOpenCodePermissionRequest}. */
export type OpenCodePermissionResponse = 'once' | 'always' | 'reject'

/** A server-sent event from `GET /event`. */
export interface IOpenCodeEvent {
  readonly type: string
  readonly properties: Record<string, unknown>
}

/**
 * Extracts a displayable message from the `error` field of an assistant
 * message, which the server types as an open union of error objects.
 */
export function getOpenCodeErrorText(error: unknown): string | null {
  if (error === undefined || error === null) {
    return null
  }

  if (typeof error === 'string') {
    return error
  }

  if (typeof error !== 'object') {
    return String(error)
  }

  const record = error as Record<string, unknown>
  const data = record.data

  if (typeof data === 'object' && data !== null) {
    const message = (data as Record<string, unknown>).message
    if (typeof message === 'string' && message.length > 0) {
      return message
    }
  }

  if (typeof record.message === 'string' && record.message.length > 0) {
    return record.message
  }

  if (typeof record.name === 'string' && record.name.length > 0) {
    return record.name
  }

  return 'The agent run failed.'
}
